---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: {{ include "openstack-cluster.clusterName" . }}
  labels: {{ include "openstack-cluster.labels" . | nindent 4 }}
  annotations:
    # We let Cluster API clean up this resource
    # Deleting it ourselves, which CAPI is not expecting, can cause some nasty race conditions
    helm.sh/resource-policy: keep
    # NOTE: Argo won't delete this object itself as it has an owner reference to the cluster
spec:
  identityRef:
    name: {{ include "openstack-cluster.cloudCredentialsSecretName" . }}
    cloudName: openstack
  {{- with .Values.controlPlaneEndpoint }}
  controlPlaneEndpoint: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.clusterNetworking }}
  {{- if .manageSecurityGroups }}
  managedSecurityGroups:
    {{- if eq .manageSecurityGroups "true" }}
    allowAllInClusterTraffic: {{ .allowAllInClusterTraffic }}
    {{- else }}
    {{- toYaml .manageSecurityGroups | nindent 2 }}
    {{- end }}
  {{- end }}
  disableExternalNetwork: {{ .disableExternalNetwork | default "false" }}
  {{- if or .externalNetworkFilter .externalNetworkId }}
  externalNetwork:
    {{- if .externalNetworkFilter }}
    {{- toYaml .externalNetworkFilter | nindent 2 }}
    {{- else }}
    id: {{ .externalNetworkId }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- with .internalNetwork }}
  {{- if or .networkFilter .subnetFilter .subnets }}
  {{- with .networkFilter }}
  network: {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- if or .subnets .subnetFilter }}
  subnets:
  {{- if .subnets }}
  {{- toYaml .subnets | nindent 2 }}
  {{- else }}
  - {{ toYaml .subnetFilter | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- else }}
  managedSubnets:
  {{- if .managedSubnets }}
  {{- toYaml .managedSubnets | nindent 2 }}
  {{- else }}
  - cidr: {{ .nodeCidr }}
    dnsNameservers: {{ toYaml .Values.dnsNameservers | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}

  {{- with .Values.apiServer }}
  {{- if .enableLoadBalancer }}
  apiServerLoadBalancer:
    enabled: true
  {{- if .loadBalancerProvider }}
    provider: {{ .loadBalancerProvider }}
  {{- end }}
  {{- if or .allowedCidrs .allowedCIDRs }}
    allowedCIDRs:
      {{- range .allowedCidrs | default .allowedCIDRs }}
      - {{ . }}
      {{- end}}
  {{- end }}
  {{- end }}
  disableAPIServerFloatingIP: {{ not .associateFloatingIP }}
  {{- with .floatingIP }}
  apiServerFloatingIP: {{ . }}
  {{- end }}
  {{- with .fixedIP }}
  apiServerFixedIP: {{ . }}
  {{- end }}
  apiServerPort: {{ .port }}
  {{- end }}
  {{- with .Values.controlPlane }}
  {{- if .omitFailureDomain }}
  controlPlaneOmitAvailabilityZone: true
  {{- else if .failureDomains }}
  controlPlaneAvailabilityZones: {{ toYaml .failureDomains | nindent 4 }}
  {{- end }}
  {{- end }}
